# Generated by Django 4.2.15 on 2025-04-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saler_car_details",
            name="bidding_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="saler_car_details",
            name="bidding_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="saler_car_details",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("in_inspection", "In Inspection"),
                    ("await_approval", " Awating Approval"),
                    ("rejected", "Rejected"),
                    ("bidding", "In Bidding"),
                    ("expired", "Expired"),
                    ("sold", "Sold"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
