# Generated by Django 4.2.21 on 2025-08-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="min_bid_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=60, null=True
            ),
        ),
        migrations.AddField(
            model_name="saler_car_details",
            name="min_bid_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=60, null=True
            ),
        ),
    ]
