# Generated by Django 4.2.21 on 2025-05-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saler_car_details",
            old_name="max_range",
            new_name="demand",
        ),
        migrations.RemoveField(
            model_name="saler_car_details",
            name="min_range",
        ),
    ]
