# Generated by Django 4.2.21 on 2025-05-29 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionreport",
            name="guest_car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_inspection_reports",
                to="sabac.guest",
            ),
        ),
        migrations.AlterField(
            model_name="inspectionreport",
            name="saler_car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspection_reports",
                to="sabac.saler_car_details",
            ),
        ),
    ]
