# Generated by Django 4.2.21 on 2025-09-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("in_inspection", "In Inspection"),
                    ("await_approval", " Awating Approval"),
                    ("rejected", "Rejected"),
                    ("bidding", "In Bidding"),
                    ("expired", "Expired"),
                    ("in_inventory", "In Inventory"),
                    ("sold", "Sold"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="saler_car_details",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("in_inspection", "In Inspection"),
                    ("await_approval", " Awating Approval"),
                    ("rejected", "Rejected"),
                    ("bidding", "In Bidding"),
                    ("expired", "Expired"),
                    ("in_inventory", "In Inventory"),
                    ("sold", "Sold"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
