# Generated by Django 4.2.21 on 2025-05-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saler_car_details",
            name="inspection_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
