# Generated by Django 4.2.21 on 2025-05-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0002_alter_inspectionreport_guest_car_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saler_car_details",
            old_name="inspector",
            new_name="inspector_id",
        ),
    ]
