# Generated by Django 4.2.21 on 2025-05-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0002_rename_max_range_saler_car_details_demand_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guest",
            old_name="max_range",
            new_name="demand",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="min_range",
        ),
    ]
