# Generated by Django 4.2.21 on 2025-05-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0002_alter_saler_car_details_inspection_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="saler_car_details",
            name="max_range",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=60, null=True
            ),
        ),
        migrations.AddField(
            model_name="saler_car_details",
            name="min_range",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=60, null=True
            ),
        ),
    ]
