# Generated by Django 4.2.15 on 2025-04-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0002_saler_car_details_bidding_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saler_car_details",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
