# Generated by Django 4.2.21 on 2025-05-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0003_rename_inspector_saler_car_details_inspector_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saler_car_details",
            old_name="inspector_id",
            new_name="inspector",
        ),
    ]
