# Generated by Django 4.2.21 on 2025-09-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0003_devicedetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saler_car_details",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("in_inspection", "In Inspection"),
                    ("await_approval", "Awaiting Approval"),
                    ("rejected", "Rejected"),
                    ("bidding", "In Bidding"),
                    ("expired", "Expired"),
                    ("in_inventory", "In Inventory"),
                    ("sold", "Sold"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
