# Generated by Django 4.2.15 on 2025-05-06 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0003_alter_saler_car_details_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="saler_car_details",
            name="winner_dealer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dealer_inventory_cars",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="saler_car_details",
            name="guest",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guest_owner_cars",
                to="sabac.guest",
            ),
        ),
        migrations.AlterField(
            model_name="saler_car_details",
            name="inspector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspector_connected",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="saler_car_details",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_car",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
