# Generated by Django 4.2.21 on 2025-05-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0003_rename_max_range_guest_demand_remove_guest_min_range"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="primary_phone_number",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="secondary_phone_number",
        ),
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="guest",
            name="number",
            field=models.CharField(max_length=30),
        ),
    ]
