# Generated by Django 4.2.15 on 2025-05-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0004_saler_car_details_winner_dealer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidding",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
