# Generated by Django 4.2.21 on 2025-05-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0004_remove_guest_primary_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selectedslot",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sabac.guest",
            ),
        ),
    ]
