# Generated by Django 4.2.21 on 2025-05-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0004_rename_inspector_id_saler_car_details_inspector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
