# Generated by Django 4.2.21 on 2025-05-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0005_selectedslot_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selectedslot",
            name="booked_by",
            field=models.CharField(
                choices=[
                    ("seler", "Seller"),
                    ("inspector", "Inspector"),
                    ("guest", "Guest"),
                ],
                default="seller",
                max_length=10,
            ),
        ),
    ]
