# Generated by Django 4.2.21 on 2025-05-31 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0005_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidding",
            name="guest_car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_car_bid",
                to="sabac.guest",
            ),
        ),
        migrations.AlterField(
            model_name="bidding",
            name="saler_car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="sabac.saler_car_details",
            ),
        ),
    ]
