# Generated by Django 4.2.21 on 2025-05-31 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0006_bidding_guest_car_alter_bidding_saler_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="guest_car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="sabac.guest",
            ),
        ),
    ]
