# Generated by Django 4.2.15 on 2025-05-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0006_devicetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saler_car_details",
            name="inspection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="saler_car_details",
            name="inspection_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="CarPhoto",
        ),
    ]
