# Generated by Django 4.2.20 on 2025-05-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0006_devicetoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CarPhoto",
        ),
    ]
