# Generated by Django 4.2.21 on 2025-05-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0006_alter_selectedslot_booked_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selectedslot",
            old_name="guest",
            new_name="unreg_guest",
        ),
    ]
