# Generated by Django 4.2.21 on 2025-06-02 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0007_notification_guest_car"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignslot",
            name="date",
        ),
        migrations.RemoveField(
            model_name="assignslot",
            name="time_slot",
        ),
        migrations.AddField(
            model_name="assignslot",
            name="guest_car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_slot_to_guest",
                to="sabac.guest",
            ),
        ),
        migrations.AddField(
            model_name="assignslot",
            name="inspection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignslot",
            name="inspection_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="assignslot",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_slots",
                to="sabac.saler_car_details",
            ),
        ),
    ]
