# Generated by Django 4.2.20 on 2025-05-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0007_delete_carphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidding",
            name="bid_amount",
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
    ]
