# Generated by Django 4.2.21 on 2025-06-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0008_remove_assignslot_date_remove_assignslot_time_slot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saler_car_details",
            name="inspection_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
