# Generated by Django 4.2.21 on 2025-06-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0009_alter_saler_car_details_inspection_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="car_variant",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="inspectionreport",
            name="image_urls",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="saler_car_details",
            name="car_variant",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
