# Generated by Django 4.2.21 on 2025-07-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sabac", "0010_guest_car_variant_inspectionreport_image_urls_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plain_password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
